-- V3.2 FINAL migration. Development source of truth.
-- Generated by semantic reconciliation of the V3.1 baseline.
-- Do not run the monolithic baseline and these migrations together on the same database.

-- File: 003_core_tenant.sql

-- 3. HELPER FUNCTIONS
-- =============================================================================

CREATE OR REPLACE FUNCTION current_tenant_id()
RETURNS UUID
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN (
        NULLIF(
            current_setting('request.jwt.claims', true)::json
                ->'app_metadata'->>'tenant_id',
            ''
        )
    )::UUID;
EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- Memastikan FK lintas tenant tidak dapat dibuat secara tidak sengaja.
CREATE OR REPLACE FUNCTION enforce_same_tenant()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    parent_tenant UUID;
    parent_table TEXT := TG_ARGV[0];
    parent_id UUID;
BEGIN
    parent_id := (to_jsonb(NEW)->>TG_ARGV[2])::UUID;

    IF parent_id IS NULL THEN
        RETURN NEW;
    END IF;

    -- SECURITY DEFINER is required here: otherwise RLS can hide a parent row
    -- belonging to another tenant and make the cross-tenant check appear valid.
    EXECUTE format(
        'SELECT tenant_id FROM %I WHERE id = $1',
        parent_table
    )
    INTO parent_tenant
    USING parent_id;

    IF parent_tenant IS NULL THEN
        RAISE EXCEPTION 'Referenced tenant-owned record was not found';
    END IF;

    IF NEW.tenant_id IS DISTINCT FROM parent_tenant THEN
        RAISE EXCEPTION 'Cross-tenant reference is not allowed';
    END IF;

    RETURN NEW;
END;
$$;

-- =============================================================================

-- 4. TENANT, VENDOR CATEGORY & PROFILE
-- =============================================================================

CREATE TABLE IF NOT EXISTS tenants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    logo_url TEXT,
    banner_url TEXT,
    status vendor_status_enum NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS vendor_categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) UNIQUE NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS vendor_profiles (
    tenant_id UUID PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
    category_id UUID NOT NULL REFERENCES vendor_categories(id) ON DELETE RESTRICT,
    description TEXT,
    city VARCHAR(100) NOT NULL,
    address TEXT,
    minimum_price NUMERIC(15,2) NOT NULL DEFAULT 0 CHECK (minimum_price >= 0),
    gallery_portfolio JSONB NOT NULL DEFAULT '[]'::jsonb,
    social_media JSONB NOT NULL DEFAULT '{}'::jsonb,
    bank_account_info JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Data aman untuk marketplace. Jangan expose bank_account_info dari vendor_profiles.
CREATE TABLE IF NOT EXISTS vendor_public_listings (
    tenant_id UUID PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
    category_id UUID NOT NULL REFERENCES vendor_categories(id) ON DELETE RESTRICT,
    display_name VARCHAR(255) NOT NULL,
    slug VARCHAR(150) UNIQUE NOT NULL,
    description TEXT,
    city VARCHAR(100),
    logo_url TEXT,
    banner_url TEXT,
    gallery JSONB NOT NULL DEFAULT '[]'::jsonb,
    social_media JSONB NOT NULL DEFAULT '{}'::jsonb,
    minimum_price NUMERIC(15,2) NOT NULL DEFAULT 0 CHECK (minimum_price >= 0),
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
