-- V3.2 FINAL migration. Development source of truth.
-- Generated by semantic reconciliation of the V3.1 baseline.
-- Do not run the monolithic baseline and these migrations together on the same database.

-- File: 004_users_permissions.sql

-- 5. USERS / TEAM
-- =============================================================================

CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50),
    role user_role_enum NOT NULL DEFAULT 'staff',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(tenant_id, email)
);

-- Resolve tenant from a trusted app_metadata claim when present, then fall back
-- to the authenticated user's profile. This avoids requiring a custom JWT claim
-- before ordinary tenant RLS can work. The function only trusts auth.uid() for the
-- profile lookup; do not use user_metadata for tenant identity.
CREATE OR REPLACE FUNCTION current_tenant_id()
RETURNS UUID
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    claim_tenant UUID;
    profile_tenant UUID;
BEGIN
    BEGIN
        claim_tenant := NULLIF(
            current_setting('request.jwt.claims', true)::json
                ->'app_metadata'->>'tenant_id',
            ''
        )::UUID;
    EXCEPTION
        WHEN OTHERS THEN
            claim_tenant := NULL;
    END;

    IF claim_tenant IS NOT NULL THEN
        RETURN claim_tenant;
    END IF;

    SELECT p.tenant_id
      INTO profile_tenant
      FROM public.profiles p
     WHERE p.id = auth.uid()
       AND p.is_active = TRUE
     LIMIT 1;

    RETURN profile_tenant;
END;
$$;

-- =============================================================================

-- 6. PLATFORM MODULES, VENDOR MODULES, ROLES
-- =============================================================================

CREATE TABLE IF NOT EXISTS platform_modules (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    is_core BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS vendor_category_modules (
    vendor_category_id UUID NOT NULL REFERENCES vendor_categories(id) ON DELETE CASCADE,
    module_id UUID NOT NULL REFERENCES platform_modules(id) ON DELETE CASCADE,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    PRIMARY KEY (vendor_category_id, module_id)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    role user_role_enum NOT NULL,
    module_id UUID NOT NULL REFERENCES platform_modules(id) ON DELETE CASCADE,
    can_view BOOLEAN NOT NULL DEFAULT FALSE,
    can_create BOOLEAN NOT NULL DEFAULT FALSE,
    can_update BOOLEAN NOT NULL DEFAULT FALSE,
    can_delete BOOLEAN NOT NULL DEFAULT FALSE,
    can_export BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(role, module_id)
);

-- =============================================================================
