-- V3.2 FINAL migration. Development source of truth.
-- Generated by semantic reconciliation of the V3.1 baseline.
-- Do not run the monolithic baseline and these migrations together on the same database.

-- File: 005_clients_services.sql

-- 7. CLIENTS
-- =============================================================================

CREATE TABLE IF NOT EXISTS clients (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone_number VARCHAR(50),
    company_name VARCHAR(255),
    address TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================

-- 8. SERVICES / PACKAGES / PROMO
-- =============================================================================

CREATE TABLE IF NOT EXISTS vendor_services (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    pricing_type pricing_type_enum NOT NULL DEFAULT 'fixed_package',
    base_price NUMERIC(15,2) NOT NULL DEFAULT 0 CHECK (base_price >= 0),
    min_order_qty INT NOT NULL DEFAULT 1 CHECK (min_order_qty >= 1),
    specifications JSONB NOT NULL DEFAULT '{}'::jsonb,
    image_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS promo_codes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    code VARCHAR(50) NOT NULL,
    discount_amount NUMERIC(15,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    discount_type VARCHAR(20) NOT NULL DEFAULT 'fixed'
        CHECK (discount_type IN ('fixed', 'percentage')),
    max_uses INT NOT NULL DEFAULT 0 CHECK (max_uses >= 0),
    uses_count INT NOT NULL DEFAULT 0 CHECK (uses_count >= 0),
    valid_from TIMESTAMPTZ,
    valid_until TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(tenant_id, code)
);

-- =============================================================================
