-- V3.2 FINAL migration. Development source of truth.
-- Generated by semantic reconciliation of the V3.1 baseline.
-- Do not run the monolithic baseline and these migrations together on the same database.

-- File: 008_finance.sql

-- 11. FINANCE / TRANSACTIONS
-- =============================================================================

CREATE TABLE IF NOT EXISTS transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    booking_id UUID REFERENCES vendor_bookings(id) ON DELETE SET NULL,
    invoice_id UUID,
    transaction_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    type transaction_type_enum NOT NULL,
    amount NUMERIC(15,2) NOT NULL CHECK (amount > 0),
    description TEXT NOT NULL,
    payment_method VARCHAR(50),
    reference_id VARCHAR(255),
    proof_of_payment_url TEXT,
    created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================

-- 12. INVOICES
-- =============================================================================

CREATE TABLE IF NOT EXISTS invoices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    booking_id UUID NOT NULL REFERENCES vendor_bookings(id) ON DELETE CASCADE,
    invoice_number VARCHAR(100) NOT NULL,
    payment_stage VARCHAR(50) NOT NULL
        CHECK (payment_stage IN ('down_payment','installment','final_payment')),
    amount NUMERIC(15,2) NOT NULL CHECK (amount > 0),
    due_date TIMESTAMPTZ NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'unpaid'
        CHECK (status IN ('unpaid','paid','overdue','canceled')),
    paid_at TIMESTAMPTZ,
    payment_link TEXT,
    payment_reference_id VARCHAR(255),
    payment_method VARCHAR(50),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(tenant_id, invoice_number)
);

ALTER TABLE transactions
    DROP CONSTRAINT IF EXISTS transactions_invoice_id_fkey;

ALTER TABLE transactions
    ADD CONSTRAINT transactions_invoice_id_fkey
    FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL;

-- =============================================================================

-- 13. CONTRACTS
-- =============================================================================

CREATE TABLE IF NOT EXISTS contracts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    booking_id UUID NOT NULL REFERENCES vendor_bookings(id) ON DELETE CASCADE,
    contract_number VARCHAR(100) NOT NULL,
    terms_and_conditions TEXT NOT NULL,
    scope_of_work JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(30) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft','sent','signed','rejected','void')),
    client_signed_at TIMESTAMPTZ,
    vendor_signed_at TIMESTAMPTZ,
    client_signature_url TEXT,
    vendor_signature_url TEXT,
    pdf_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(tenant_id, contract_number)
);

-- =============================================================================

-- 14. PORTFOLIO
-- =============================================================================

CREATE TABLE IF NOT EXISTS portfolios (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    description TEXT,
    event_date DATE,
    venue_name VARCHAR(255),
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(tenant_id, slug)
);

CREATE TABLE IF NOT EXISTS portfolio_media (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    portfolio_id UUID NOT NULL REFERENCES portfolios(id) ON DELETE CASCADE,
    media_type VARCHAR(20) NOT NULL CHECK (media_type IN ('image','video')),
    media_url TEXT NOT NULL,
    thumbnail_url TEXT,
    caption TEXT,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
