-- V3.2 FINAL migration. Development source of truth.
-- Generated by semantic reconciliation of the V3.1 baseline.
-- Do not run the monolithic baseline and these migrations together on the same database.

-- File: 002_enums.sql

-- 2. ENUM TYPES (IDEMPOTENT)
-- =============================================================================

DO $$ BEGIN
    CREATE TYPE vendor_status_enum AS ENUM ('active', 'suspended', 'pending_approval');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE user_role_enum AS ENUM ('owner', 'admin', 'staff', 'freelancer');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE pricing_type_enum AS ENUM ('fixed_package', 'per_pax', 'per_hour', 'custom_quote');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE booking_status_enum AS ENUM ('pending', 'confirmed', 'in_progress', 'completed', 'canceled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE payment_status_enum AS ENUM ('unpaid', 'dp_paid', 'fully_paid', 'refunded');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE transaction_type_enum AS ENUM ('income', 'expense', 'payout');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- =============================================================================

-- 29. ADDITIONAL ENUMS
-- ---------------------------------------------------------------------------
DO $$ BEGIN
    CREATE TYPE subscription_status_enum AS ENUM
    ('trialing','active','past_due','paused','canceled','expired');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE billing_interval_enum AS ENUM ('monthly','yearly','lifetime');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE subscription_payment_status_enum AS ENUM
    ('pending','paid','failed','refunded','canceled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE platform_admin_role_enum AS ENUM
    ('super_admin','support_admin','finance_admin','content_admin');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE audit_action_enum AS ENUM
    ('create','update','delete','restore','suspend','activate','login','logout',
     'subscription_change','payment_update','impersonation_start','impersonation_end');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------------------
