-- V3.2 FINAL migration. Development source of truth.
-- Generated by semantic reconciliation of the V3.1 baseline.
-- Do not run the monolithic baseline and these migrations together on the same database.

-- File: 009_inventory.sql

-- 15. INVENTORY
-- =============================================================================

CREATE TABLE IF NOT EXISTS inventory_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(tenant_id, name)
);

CREATE TABLE IF NOT EXISTS inventory_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    category_id UUID REFERENCES inventory_categories(id) ON DELETE SET NULL,
    sku VARCHAR(100),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    unit VARCHAR(50) NOT NULL DEFAULT 'pcs',
    current_stock NUMERIC(15,3) NOT NULL DEFAULT 0,
    minimum_stock NUMERIC(15,3) NOT NULL DEFAULT 0 CHECK (minimum_stock >= 0),
    purchase_price NUMERIC(15,2) NOT NULL DEFAULT 0 CHECK (purchase_price >= 0),
    supplier_name VARCHAR(255),
    storage_location VARCHAR(255),
    status VARCHAR(30) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active','inactive','damaged','maintenance')),
    image_url TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(tenant_id, sku)
);

-- quantity_delta sengaja signed:
-- + = masuk, - = keluar/dipakai/rusak.
CREATE TABLE IF NOT EXISTS inventory_stock_movements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    inventory_item_id UUID NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
    movement_type VARCHAR(30) NOT NULL
        CHECK (movement_type IN ('in','out','adjustment','return','damaged')),
    quantity_delta NUMERIC(15,3) NOT NULL CHECK (quantity_delta <> 0),
    reference_type VARCHAR(50),
    reference_id UUID,
    notes TEXT,
    created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION apply_inventory_stock_movement()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    new_stock NUMERIC(15,3);
BEGIN
    UPDATE inventory_items
    SET current_stock = current_stock + NEW.quantity_delta,
        updated_at = NOW()
    WHERE id = NEW.inventory_item_id
      AND tenant_id = NEW.tenant_id
    RETURNING current_stock INTO new_stock;

    IF new_stock IS NULL THEN
        RAISE EXCEPTION 'Inventory item tidak ditemukan atau tenant tidak cocok';
    END IF;

    IF new_stock < 0 THEN
        RAISE EXCEPTION 'Stock tidak boleh menjadi negatif';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_apply_inventory_stock_movement
AFTER INSERT ON inventory_stock_movements
FOR EACH ROW EXECUTE FUNCTION apply_inventory_stock_movement();

-- =============================================================================
