-- V3.2 FINAL migration. Development source of truth.
-- Generated by semantic reconciliation of the V3.1 baseline.
-- Do not run the monolithic baseline and these migrations together on the same database.

-- File: 011_workflows.sql

-- 21. GENERIC WORKFLOW
-- =============================================================================

CREATE TABLE IF NOT EXISTS vendor_workflows (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vendor_category_id UUID NOT NULL REFERENCES vendor_categories(id) ON DELETE CASCADE,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(vendor_category_id, code)
);

CREATE TABLE IF NOT EXISTS workflow_stages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workflow_id UUID NOT NULL REFERENCES vendor_workflows(id) ON DELETE CASCADE,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    display_order INT NOT NULL DEFAULT 0,
    is_terminal BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(workflow_id, code)
);

CREATE TABLE IF NOT EXISTS booking_workflow_states (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    booking_id UUID NOT NULL REFERENCES vendor_bookings(id) ON DELETE CASCADE,
    workflow_id UUID NOT NULL REFERENCES vendor_workflows(id) ON DELETE RESTRICT,
    current_stage_id UUID REFERENCES workflow_stages(id) ON DELETE SET NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    UNIQUE(booking_id)
);

CREATE TABLE IF NOT EXISTS booking_workflow_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    booking_id UUID NOT NULL REFERENCES vendor_bookings(id) ON DELETE CASCADE,
    from_stage_id UUID REFERENCES workflow_stages(id) ON DELETE SET NULL,
    to_stage_id UUID REFERENCES workflow_stages(id) ON DELETE SET NULL,
    changed_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    notes TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
