-- V3.2 FINAL migration. Development source of truth.
-- Generated by semantic reconciliation of the V3.1 baseline.
-- Do not run the monolithic baseline and these migrations together on the same database.

-- File: 014_hardening_rls.sql

-- 22. INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_profiles_tenant_active
    ON profiles(tenant_id, is_active);

CREATE INDEX IF NOT EXISTS idx_clients_tenant_name
    ON clients(tenant_id, full_name);

CREATE INDEX IF NOT EXISTS idx_services_tenant_active
    ON vendor_services(tenant_id, is_active);

CREATE INDEX IF NOT EXISTS idx_bookings_tenant_status
    ON vendor_bookings(tenant_id, status);

CREATE INDEX IF NOT EXISTS idx_bookings_tenant_event_date
    ON vendor_bookings(tenant_id, event_date);

CREATE INDEX IF NOT EXISTS idx_bookings_tenant_client
    ON vendor_bookings(tenant_id, client_id);

CREATE INDEX IF NOT EXISTS idx_transactions_tenant_date
    ON transactions(tenant_id, transaction_date);

CREATE INDEX IF NOT EXISTS idx_invoices_tenant_status_due
    ON invoices(tenant_id, status, due_date);

CREATE INDEX IF NOT EXISTS idx_quotations_tenant_status
    ON quotations(tenant_id, status);

CREATE INDEX IF NOT EXISTS idx_portfolios_tenant_published
    ON portfolios(tenant_id, is_published);

CREATE INDEX IF NOT EXISTS idx_portfolio_media
    ON portfolio_media(tenant_id, portfolio_id, display_order);

CREATE INDEX IF NOT EXISTS idx_inventory_items_tenant_status
    ON inventory_items(tenant_id, status);

CREATE INDEX IF NOT EXISTS idx_inventory_movements_item_date
    ON inventory_stock_movements(tenant_id, inventory_item_id, created_at);

CREATE INDEX IF NOT EXISTS idx_team_assignment_booking
    ON project_team_assignments(tenant_id, booking_id);

CREATE INDEX IF NOT EXISTS idx_workflow_history_booking
    ON booking_workflow_history(tenant_id, booking_id, changed_at);

-- =============================================================================

-- 23. RLS — ENABLE
-- =============================================================================

ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_public_listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_category_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE promo_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_team_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotation_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE portfolios ENABLE ROW LEVEL SECURITY;
ALTER TABLE portfolio_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE catering_menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE catering_menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE catering_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE photography_equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE photography_booking_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE decoration_themes ENABLE ROW LEVEL SECURITY;
ALTER TABLE decoration_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE decoration_theme_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE mua_artists ENABLE ROW LEVEL SECURITY;
ALTER TABLE mua_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE wo_rundowns ENABLE ROW LEVEL SECURITY;
ALTER TABLE wo_rundown_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_workflows ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflow_stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_workflow_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_workflow_history ENABLE ROW LEVEL SECURITY;

-- =============================================================================

-- 24. RLS — REMOVE OLD V3 POLICIES IF RE-RUN
-- =============================================================================

DO $$
DECLARE
    p RECORD;
BEGIN
    FOR p IN
        SELECT policyname, tablename
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename IN (
            'tenants','vendor_profiles','vendor_public_listings','profiles',
            'platform_modules','vendor_category_modules','role_permissions',
            'clients','vendor_services','promo_codes','vendor_bookings',
            'project_team_assignments','quotations','quotation_items',
            'transactions','invoices','contracts','portfolios','portfolio_media',
            'inventory_categories','inventory_items','inventory_stock_movements',
            'catering_menus','catering_menu_items','catering_recipes',
            'photography_equipment','photography_booking_details',
            'decoration_themes','decoration_items','decoration_theme_items',
            'mua_artists','mua_packages','wo_rundowns','wo_rundown_items',
            'vendor_workflows','workflow_stages',
            'booking_workflow_states','booking_workflow_history'
          )
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', p.policyname, p.tablename);
    END LOOP;
END $$;

-- Tenant-private tables.
CREATE POLICY tenant_isolation ON tenants
    FOR ALL USING (id = current_tenant_id())
    WITH CHECK (id = current_tenant_id());

CREATE POLICY tenant_isolation ON vendor_profiles
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON profiles
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON clients
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON vendor_services
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON promo_codes
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON vendor_bookings
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON project_team_assignments
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON quotations
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON quotation_items
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON transactions
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON invoices
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON contracts
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON portfolios
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON portfolio_media
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON inventory_categories
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON inventory_items
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON inventory_stock_movements
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON catering_menus
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON catering_menu_items
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON catering_recipes
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON photography_equipment
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON photography_booking_details
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON decoration_themes
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON decoration_items
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON decoration_theme_items
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON mua_artists
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON mua_packages
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON wo_rundowns
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON wo_rundown_items
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON booking_workflow_states
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

CREATE POLICY tenant_isolation ON booking_workflow_history
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

-- Konfigurasi platform dapat dibaca aplikasi.
CREATE POLICY platform_modules_read ON platform_modules
    FOR SELECT USING (true);

CREATE POLICY vendor_category_modules_read ON vendor_category_modules
    FOR SELECT USING (true);

CREATE POLICY role_permissions_read ON role_permissions
    FOR SELECT USING (true);

-- Workflow templates are category-global in V3.2. Vendor users may read
-- the template for their category, but may not mutate shared configuration.
CREATE POLICY workflow_category_access ON vendor_workflows
    FOR SELECT USING (
        vendor_category_id IN (
            SELECT category_id
            FROM vendor_profiles
            WHERE tenant_id = current_tenant_id()
        )
    );

CREATE POLICY workflow_stage_access ON workflow_stages
    FOR SELECT USING (
        workflow_id IN (
            SELECT vw.id
            FROM vendor_workflows vw
            JOIN vendor_profiles vp
              ON vp.category_id = vw.vendor_category_id
            WHERE vp.tenant_id = current_tenant_id()
        )
    );

-- Marketplace: hanya data yang memang dipublish.
CREATE POLICY public_listing_read ON vendor_public_listings
    FOR SELECT USING (is_published = TRUE);

CREATE POLICY owner_listing_manage ON vendor_public_listings
    FOR ALL USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());

-- Portfolio publik: hanya portfolio yang dipublish.
CREATE POLICY public_portfolio_read ON portfolios
    FOR SELECT USING (is_published = TRUE);

-- Media publik hanya mengikuti portfolio yang dapat dilihat publik.
CREATE POLICY public_portfolio_media_read ON portfolio_media
    FOR SELECT USING (
        portfolio_id IN (
            SELECT id FROM portfolios WHERE is_published = TRUE
        )
    );

-- =============================================================================

-- 25. TENANT CONSISTENCY TRIGGERS
-- =============================================================================

DROP TRIGGER IF EXISTS trg_client_tenant_check ON vendor_bookings;
CREATE TRIGGER trg_client_tenant_check
BEFORE INSERT OR UPDATE ON vendor_bookings
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('clients','tenant_id','client_id');

DROP TRIGGER IF EXISTS trg_service_tenant_check ON vendor_bookings;
CREATE TRIGGER trg_service_tenant_check
BEFORE INSERT OR UPDATE ON vendor_bookings
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('vendor_services','tenant_id','service_id');

DROP TRIGGER IF EXISTS trg_promo_tenant_check ON vendor_bookings;
CREATE TRIGGER trg_promo_tenant_check
BEFORE INSERT OR UPDATE ON vendor_bookings
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('promo_codes','tenant_id','promo_code_id');

DROP TRIGGER IF EXISTS trg_booking_profile_tenant_check ON project_team_assignments;
CREATE TRIGGER trg_booking_profile_tenant_check
BEFORE INSERT OR UPDATE ON project_team_assignments
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('vendor_bookings','tenant_id','booking_id');

DROP TRIGGER IF EXISTS trg_assignment_profile_tenant_check ON project_team_assignments;
CREATE TRIGGER trg_assignment_profile_tenant_check
BEFORE INSERT OR UPDATE ON project_team_assignments
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('profiles','tenant_id','profile_id');

DROP TRIGGER IF EXISTS trg_quotation_client_tenant_check ON quotations;
CREATE TRIGGER trg_quotation_client_tenant_check
BEFORE INSERT OR UPDATE ON quotations
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('clients','tenant_id','client_id');

DROP TRIGGER IF EXISTS trg_quotation_booking_tenant_check ON quotations;
CREATE TRIGGER trg_quotation_booking_tenant_check
BEFORE INSERT OR UPDATE ON quotations
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('vendor_bookings','tenant_id','booking_id');

DROP TRIGGER IF EXISTS trg_quotation_item_tenant_check ON quotation_items;
CREATE TRIGGER trg_quotation_item_tenant_check
BEFORE INSERT OR UPDATE ON quotation_items
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('quotations','tenant_id','quotation_id');

DROP TRIGGER IF EXISTS trg_invoice_booking_tenant_check ON invoices;
CREATE TRIGGER trg_invoice_booking_tenant_check
BEFORE INSERT OR UPDATE ON invoices
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('vendor_bookings','tenant_id','booking_id');

DROP TRIGGER IF EXISTS trg_transaction_booking_tenant_check ON transactions;
CREATE TRIGGER trg_transaction_booking_tenant_check
BEFORE INSERT OR UPDATE ON transactions
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('vendor_bookings','tenant_id','booking_id');

DROP TRIGGER IF EXISTS trg_transaction_invoice_tenant_check ON transactions;
CREATE TRIGGER trg_transaction_invoice_tenant_check
BEFORE INSERT OR UPDATE ON transactions
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('invoices','tenant_id','invoice_id');

DROP TRIGGER IF EXISTS trg_contract_booking_tenant_check ON contracts;
CREATE TRIGGER trg_contract_booking_tenant_check
BEFORE INSERT OR UPDATE ON contracts
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('vendor_bookings','tenant_id','booking_id');

DROP TRIGGER IF EXISTS trg_media_portfolio_tenant_check ON portfolio_media;
CREATE TRIGGER trg_media_portfolio_tenant_check
BEFORE INSERT OR UPDATE ON portfolio_media
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('portfolios','tenant_id','portfolio_id');

DROP TRIGGER IF EXISTS trg_inventory_category_tenant_check ON inventory_items;
CREATE TRIGGER trg_inventory_category_tenant_check
BEFORE INSERT OR UPDATE ON inventory_items
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('inventory_categories','tenant_id','category_id');

DROP TRIGGER IF EXISTS trg_inventory_movement_tenant_check ON inventory_stock_movements;
CREATE TRIGGER trg_inventory_movement_tenant_check
BEFORE INSERT OR UPDATE ON inventory_stock_movements
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('inventory_items','tenant_id','inventory_item_id');

DROP TRIGGER IF EXISTS trg_catering_menu_item_tenant_check ON catering_menu_items;
CREATE TRIGGER trg_catering_menu_item_tenant_check
BEFORE INSERT OR UPDATE ON catering_menu_items
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('catering_menus','tenant_id','menu_id');

DROP TRIGGER IF EXISTS trg_catering_recipe_menu_tenant_check ON catering_recipes;
CREATE TRIGGER trg_catering_recipe_menu_tenant_check
BEFORE INSERT OR UPDATE ON catering_recipes
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('catering_menu_items','tenant_id','menu_item_id');

DROP TRIGGER IF EXISTS trg_catering_recipe_inventory_tenant_check ON catering_recipes;
CREATE TRIGGER trg_catering_recipe_inventory_tenant_check
BEFORE INSERT OR UPDATE ON catering_recipes
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('inventory_items','tenant_id','inventory_item_id');

DROP TRIGGER IF EXISTS trg_photo_equipment_inventory_tenant_check ON photography_equipment;
CREATE TRIGGER trg_photo_equipment_inventory_tenant_check
BEFORE INSERT OR UPDATE ON photography_equipment
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('inventory_items','tenant_id','inventory_item_id');

DROP TRIGGER IF EXISTS trg_photo_detail_booking_tenant_check ON photography_booking_details;
CREATE TRIGGER trg_photo_detail_booking_tenant_check
BEFORE INSERT OR UPDATE ON photography_booking_details
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('vendor_bookings','tenant_id','booking_id');

DROP TRIGGER IF EXISTS trg_decoration_item_inventory_tenant_check ON decoration_items;
CREATE TRIGGER trg_decoration_item_inventory_tenant_check
BEFORE INSERT OR UPDATE ON decoration_items
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('inventory_items','tenant_id','inventory_item_id');

DROP TRIGGER IF EXISTS trg_decoration_theme_item_tenant_check ON decoration_theme_items;
CREATE TRIGGER trg_decoration_theme_item_tenant_check
BEFORE INSERT OR UPDATE ON decoration_theme_items
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('decoration_themes','tenant_id','theme_id');

DROP TRIGGER IF EXISTS trg_decoration_theme_item_2_tenant_check ON decoration_theme_items;
CREATE TRIGGER trg_decoration_theme_item_2_tenant_check
BEFORE INSERT OR UPDATE ON decoration_theme_items
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('decoration_items','tenant_id','decoration_item_id');

DROP TRIGGER IF EXISTS trg_mua_artist_profile_tenant_check ON mua_artists;
CREATE TRIGGER trg_mua_artist_profile_tenant_check
BEFORE INSERT OR UPDATE ON mua_artists
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('profiles','tenant_id','profile_id');

DROP TRIGGER IF EXISTS trg_wo_rundown_booking_tenant_check ON wo_rundowns;
CREATE TRIGGER trg_wo_rundown_booking_tenant_check
BEFORE INSERT OR UPDATE ON wo_rundowns
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('vendor_bookings','tenant_id','booking_id');

DROP TRIGGER IF EXISTS trg_wo_item_rundown_tenant_check ON wo_rundown_items;
CREATE TRIGGER trg_wo_item_rundown_tenant_check
BEFORE INSERT OR UPDATE ON wo_rundown_items
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('wo_rundowns','tenant_id','rundown_id');

DROP TRIGGER IF EXISTS trg_workflow_state_booking_tenant_check ON booking_workflow_states;
CREATE TRIGGER trg_workflow_state_booking_tenant_check
BEFORE INSERT OR UPDATE ON booking_workflow_states
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('vendor_bookings','tenant_id','booking_id');

DROP TRIGGER IF EXISTS trg_workflow_history_booking_tenant_check ON booking_workflow_history;
CREATE TRIGGER trg_workflow_history_booking_tenant_check
BEFORE INSERT OR UPDATE ON booking_workflow_history
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('vendor_bookings','tenant_id','booking_id');

DROP TRIGGER IF EXISTS trg_workflow_history_profile_tenant_check ON booking_workflow_history;
CREATE TRIGGER trg_workflow_history_profile_tenant_check
BEFORE INSERT OR UPDATE ON booking_workflow_history
FOR EACH ROW EXECUTE FUNCTION enforce_same_tenant('profiles','tenant_id','changed_by');

-- =============================================================================

-- 26. UPDATED_AT TRIGGERS
-- =============================================================================

DO $$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'tenants','vendor_profiles','vendor_public_listings','profiles',
        'clients','vendor_services','quotations','invoices','contracts',
        'portfolios','inventory_items','catering_menus',
        'photography_equipment','photography_booking_details',
        'decoration_themes','mua_packages','wo_rundowns'
    ]
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_updated_at ON %I', t);
        EXECUTE format(
            'CREATE TRIGGER trg_updated_at BEFORE UPDATE ON %I
             FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()',
            t
        );
    END LOOP;
END $$;

-- =============================================================================

-- 35. CORE RELATION HARDENING
-- ---------------------------------------------------------------------------
-- Profiles should belong to a real auth user when the row is provisioned.
DO $$ BEGIN
    ALTER TABLE profiles
        ADD CONSTRAINT profiles_id_auth_users_fk
        FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Prevent the same tenant from attaching a subscription payment to another tenant.
CREATE OR REPLACE FUNCTION enforce_subscription_same_tenant()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    parent_tenant UUID;
BEGIN
    SELECT tenant_id INTO parent_tenant
    FROM subscriptions
    WHERE id = NEW.subscription_id;

    IF parent_tenant IS NULL THEN
        RAISE EXCEPTION 'Subscription not found';
    END IF;

    IF NEW.tenant_id IS DISTINCT FROM parent_tenant THEN
        RAISE EXCEPTION 'Cross-tenant subscription reference is not allowed';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_subscription_payment_tenant_check ON subscription_payments;
CREATE TRIGGER trg_subscription_payment_tenant_check
BEFORE INSERT OR UPDATE ON subscription_payments
FOR EACH ROW EXECUTE FUNCTION enforce_subscription_same_tenant();

DROP TRIGGER IF EXISTS trg_subscription_event_tenant_check ON subscription_events;
CREATE TRIGGER trg_subscription_event_tenant_check
BEFORE INSERT OR UPDATE ON subscription_events
FOR EACH ROW EXECUTE FUNCTION enforce_subscription_same_tenant();

-- Inventory movement must use a signed delta consistent with its movement type.
DO $$ BEGIN
    ALTER TABLE inventory_stock_movements
        ADD CONSTRAINT inventory_movement_sign_check
        CHECK (
            (movement_type IN ('in','return') AND quantity_delta > 0)
            OR
            (movement_type IN ('out','damaged') AND quantity_delta < 0)
            OR
            movement_type = 'adjustment'
        );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------------------

-- 36. INDEXES
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_subscriptions_plan_status
    ON subscriptions(plan_id, status);

CREATE INDEX IF NOT EXISTS idx_subscription_payments_tenant_status
    ON subscription_payments(tenant_id, status, due_at);

CREATE INDEX IF NOT EXISTS idx_subscription_events_tenant_created
    ON subscription_events(tenant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_platform_audit_tenant_created
    ON platform_audit_logs(tenant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_platform_audit_actor_created
    ON platform_audit_logs(actor_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_vendor_status_history_tenant_created
    ON vendor_status_history(tenant_id, created_at DESC);

-- ---------------------------------------------------------------------------

-- 37. UPDATED_AT
-- ---------------------------------------------------------------------------
DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'subscription_plans',
        'subscriptions',
        'subscription_payments',
        'platform_admins',
        'platform_settings'
    ]
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_updated_at ON %I', t);
        EXECUTE format(
            'CREATE TRIGGER trg_updated_at BEFORE UPDATE ON %I
             FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()', t
        );
    END LOOP;
END $$;

-- ---------------------------------------------------------------------------

-- 38. RLS — PLATFORM ADMIN OVERRIDE
-- ---------------------------------------------------------------------------
ALTER TABLE subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_settings ENABLE ROW LEVEL SECURITY;

-- Plan catalog: public can see active public plans; platform admins can manage all.
DROP POLICY IF EXISTS subscription_plans_public_read ON subscription_plans;
CREATE POLICY subscription_plans_public_read ON subscription_plans
FOR SELECT USING (is_public = TRUE AND is_active = TRUE);

DROP POLICY IF EXISTS subscription_plans_platform_admin ON subscription_plans;
CREATE POLICY subscription_plans_platform_admin ON subscription_plans
FOR ALL USING (is_platform_admin()) WITH CHECK (is_platform_admin());

DROP POLICY IF EXISTS subscriptions_tenant_access ON subscriptions;
CREATE POLICY subscriptions_tenant_access ON subscriptions
FOR ALL USING (tenant_id = current_tenant_id() OR is_platform_admin())
WITH CHECK (tenant_id = current_tenant_id() OR is_platform_admin());

DROP POLICY IF EXISTS subscription_payments_tenant_access ON subscription_payments;
CREATE POLICY subscription_payments_tenant_access ON subscription_payments
FOR ALL USING (tenant_id = current_tenant_id() OR is_platform_admin())
WITH CHECK (tenant_id = current_tenant_id() OR is_platform_admin());

DROP POLICY IF EXISTS subscription_events_tenant_access ON subscription_events;
CREATE POLICY subscription_events_tenant_access ON subscription_events
FOR SELECT USING (tenant_id = current_tenant_id() OR is_platform_admin());

DROP POLICY IF EXISTS platform_admins_self_read ON platform_admins;
CREATE POLICY platform_admins_self_read ON platform_admins
FOR SELECT USING (user_id = auth.uid() OR is_platform_admin());

DROP POLICY IF EXISTS platform_admins_super_admin_manage ON platform_admins;
CREATE POLICY platform_admins_super_admin_manage ON platform_admins
FOR ALL USING (has_platform_role('super_admin'))
WITH CHECK (has_platform_role('super_admin'));

DROP POLICY IF EXISTS platform_audit_admin_read ON platform_audit_logs;
CREATE POLICY platform_audit_admin_read ON platform_audit_logs
FOR SELECT USING (is_platform_admin());

DROP POLICY IF EXISTS platform_audit_admin_insert ON platform_audit_logs;
CREATE POLICY platform_audit_admin_insert ON platform_audit_logs
FOR INSERT WITH CHECK (
    is_platform_admin()
    OR (
        actor_user_id = auth.uid()
        AND tenant_id = current_tenant_id()
    )
);

DROP POLICY IF EXISTS vendor_status_history_access ON vendor_status_history;
CREATE POLICY vendor_status_history_access ON vendor_status_history
FOR SELECT USING (tenant_id = current_tenant_id() OR is_platform_admin());

DROP POLICY IF EXISTS vendor_status_history_admin_insert ON vendor_status_history;
CREATE POLICY vendor_status_history_admin_insert ON vendor_status_history
FOR INSERT WITH CHECK (is_platform_admin());

DROP POLICY IF EXISTS platform_settings_admin_manage ON platform_settings;
CREATE POLICY platform_settings_admin_manage ON platform_settings
FOR ALL USING (is_platform_admin()) WITH CHECK (is_platform_admin());

-- ---------------------------------------------------------------------------

-- 39. SUPER ADMIN OVERRIDE FOR TENANT-OWNED DATA
-- ---------------------------------------------------------------------------
-- These policies deliberately allow active platform admins to inspect/manage
-- tenant data. Vendor users remain isolated by current_tenant_id().
-- Existing policies are renamed to avoid policy-name collisions.
DO $$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'tenants','vendor_profiles','vendor_public_listings','profiles','clients',
        'vendor_services','promo_codes','vendor_bookings','project_team_assignments',
        'quotations','quotation_items','transactions','invoices','contracts',
        'portfolios','portfolio_media','inventory_categories','inventory_items',
        'inventory_stock_movements','catering_menus','catering_menu_items',
        'catering_recipes','photography_equipment','photography_booking_details',
        'decoration_themes','decoration_items','decoration_theme_items',
        'mua_artists','mua_packages','wo_rundowns','wo_rundown_items',
        'booking_workflow_states','booking_workflow_history'
    ]
    LOOP
        -- Add a generic admin SELECT policy. Existing tenant policies remain.
        EXECUTE format(
            'DROP POLICY IF EXISTS platform_admin_full_access ON %I', t
        );
        EXECUTE format(
            'CREATE POLICY platform_admin_full_access ON %I
             FOR ALL USING (is_platform_admin())
             WITH CHECK (is_platform_admin())', t
        );
    END LOOP;
END $$;

-- Global configuration tables are intentionally readable, but only platform
-- admins may modify them.
DROP POLICY IF EXISTS platform_admin_vendor_categories ON vendor_categories;
CREATE POLICY vendor_categories_public_read ON vendor_categories
FOR SELECT USING (true);

CREATE POLICY platform_admin_vendor_categories ON vendor_categories
FOR ALL USING (is_platform_admin())
WITH CHECK (is_platform_admin());

DROP POLICY IF EXISTS platform_admin_module_config ON platform_modules;
CREATE POLICY platform_admin_module_config ON platform_modules
FOR ALL USING (is_platform_admin())
WITH CHECK (is_platform_admin());

DROP POLICY IF EXISTS platform_admin_category_module_config ON vendor_category_modules;
CREATE POLICY platform_admin_category_module_config ON vendor_category_modules
FOR ALL USING (is_platform_admin())
WITH CHECK (is_platform_admin());

DROP POLICY IF EXISTS platform_admin_role_permissions ON role_permissions;
CREATE POLICY platform_admin_role_permissions ON role_permissions
FOR ALL USING (is_platform_admin())
WITH CHECK (is_platform_admin());

-- Workflow templates are platform configuration in V3.
DROP POLICY IF EXISTS platform_admin_workflow_config ON vendor_workflows;
CREATE POLICY platform_admin_workflow_config ON vendor_workflows
FOR ALL USING (is_platform_admin())
WITH CHECK (is_platform_admin());

DROP POLICY IF EXISTS platform_admin_workflow_stage_config ON workflow_stages;
CREATE POLICY platform_admin_workflow_stage_config ON workflow_stages
FOR ALL USING (is_platform_admin())
WITH CHECK (is_platform_admin());

-- ---------------------------------------------------------------------------
