-- V3.2 FINAL migration. Development source of truth.
-- Generated by semantic reconciliation of the V3.1 baseline.
-- Do not run the monolithic baseline and these migrations together on the same database.

-- File: 015_seed.sql

-- 27. SEED VENDOR CATEGORIES
-- =============================================================================

INSERT INTO vendor_categories (name, slug, description) VALUES
('Catering', 'catering', 'Vendor makanan, minuman, dan layanan catering acara'),
('Dekorasi', 'dekorasi', 'Vendor dekorasi dan penataan venue acara'),
('MUA', 'mua', 'Makeup Artist dan layanan tata rias'),
('Photography', 'photography', 'Vendor fotografi dan dokumentasi'),
('Wedding Organizer', 'wedding-organizer', 'Vendor perencana dan koordinator acara')
ON CONFLICT (slug) DO NOTHING;

-- =============================================================================

-- 28. SEED MODULES
-- =============================================================================

INSERT INTO platform_modules (code, name, description, is_core) VALUES
('dashboard', 'Dashboard', 'Ringkasan operasional vendor', TRUE),
('clients', 'Clients', 'Pengelolaan klien', TRUE),
('services', 'Services / Packages', 'Layanan dan paket', TRUE),
('quotations', 'Quotations', 'Penawaran dan quotation', TRUE),
('bookings', 'Bookings / Projects', 'Booking dan proyek', TRUE),
('team', 'Team', 'Tim dan assignment', TRUE),
('finance', 'Finance', 'Transaksi dan keuangan', TRUE),
('invoices', 'Invoices', 'Tagihan dan pembayaran', TRUE),
('contracts', 'Contracts', 'Kontrak dan dokumen', TRUE),
('portfolio', 'Portfolio', 'Portofolio dan media', TRUE),
('inventory', 'Inventory', 'Stok dan pergerakan barang', FALSE),
('menu', 'Menu', 'Menu catering', FALSE),
('equipment', 'Equipment', 'Peralatan photography', FALSE),
('decoration', 'Decoration', 'Tema dan properti dekorasi', FALSE),
('mua_artists', 'MUA Artists', 'Data makeup artist', FALSE),
('rundown', 'Rundown', 'Rundown acara WO', FALSE),
('reports', 'Reports', 'Laporan', FALSE),
('settings', 'Settings', 'Pengaturan vendor', TRUE)
ON CONFLICT (code) DO NOTHING;

-- =============================================================================

-- 29. SEED MODULE MAPPING
-- =============================================================================

INSERT INTO vendor_category_modules (vendor_category_id, module_id, display_order)
SELECT vc.id, pm.id, x.display_order
FROM (VALUES
('catering','dashboard',1),('catering','clients',2),('catering','services',3),('catering','quotations',4),
('catering','bookings',5),('catering','menu',5),('catering','inventory',6),
('catering','team',7),('catering','finance',8),('catering','invoices',9),
('catering','contracts',10),('catering','portfolio',11),('catering','reports',12),
('catering','settings',13),

('photography','dashboard',1),('photography','clients',2),('photography','services',3),('photography','quotations',4),
('photography','bookings',5),('photography','equipment',5),('photography','team',6),
('photography','finance',7),('photography','invoices',8),('photography','contracts',9),
('photography','portfolio',10),('photography','reports',11),('photography','settings',12),

('dekorasi','dashboard',1),('dekorasi','clients',2),('dekorasi','services',3),('dekorasi','quotations',4),
('dekorasi','bookings',5),('dekorasi','decoration',5),('dekorasi','inventory',6),
('dekorasi','team',7),('dekorasi','finance',8),('dekorasi','invoices',9),
('dekorasi','contracts',10),('dekorasi','portfolio',11),('dekorasi','reports',12),
('dekorasi','settings',13),

('mua','dashboard',1),('mua','clients',2),('mua','services',3),('mua','quotations',4),
('mua','bookings',5),('mua','mua_artists',5),('mua','inventory',6),
('mua','team',7),('mua','finance',8),('mua','invoices',9),
('mua','contracts',10),('mua','portfolio',11),('mua','reports',12),
('mua','settings',13),

('wedding-organizer','dashboard',1),('wedding-organizer','clients',2),
('wedding-organizer','services',3),('wedding-organizer','quotations',4),('wedding-organizer','bookings',5),
('wedding-organizer','rundown',5),('wedding-organizer','team',6),
('wedding-organizer','finance',7),('wedding-organizer','invoices',8),
('wedding-organizer','contracts',9),('wedding-organizer','portfolio',10),
('wedding-organizer','reports',11),('wedding-organizer','settings',12)
) AS x(category_slug, module_code, display_order)
JOIN vendor_categories vc ON vc.slug = x.category_slug
JOIN platform_modules pm ON pm.code = x.module_code
ON CONFLICT (vendor_category_id, module_id)
DO UPDATE SET display_order = EXCLUDED.display_order, is_enabled = TRUE;

-- =============================================================================

-- 30. SEED DEFAULT ROLE PERMISSIONS
-- =============================================================================

INSERT INTO role_permissions
    (role, module_id, can_view, can_create, can_update, can_delete, can_export)
SELECT
    r.role,
    pm.id,
    TRUE,
    CASE WHEN r.role IN ('owner','admin') THEN TRUE ELSE FALSE END,
    CASE WHEN r.role IN ('owner','admin','staff') THEN TRUE ELSE FALSE END,
    CASE WHEN r.role IN ('owner','admin') THEN TRUE ELSE FALSE END,
    CASE WHEN r.role IN ('owner','admin') THEN TRUE ELSE FALSE END
FROM (
    VALUES
    ('owner'::user_role_enum),
    ('admin'::user_role_enum),
    ('staff'::user_role_enum),
    ('freelancer'::user_role_enum)
) r(role)
CROSS JOIN platform_modules pm
ON CONFLICT (role, module_id) DO NOTHING;

-- =============================================================================

-- 31. SEED WORKFLOWS
-- =============================================================================

INSERT INTO vendor_workflows
    (vendor_category_id, code, name, description, is_default)
SELECT id, 'catering_default', 'Catering Event Workflow',
       'Lead hingga event selesai', TRUE
FROM vendor_categories WHERE slug = 'catering'
ON CONFLICT (vendor_category_id, code) DO NOTHING;

INSERT INTO vendor_workflows
    (vendor_category_id, code, name, description, is_default)
SELECT id, 'photography_default', 'Photography Workflow',
       'Lead hingga delivery hasil foto', TRUE
FROM vendor_categories WHERE slug = 'photography'
ON CONFLICT (vendor_category_id, code) DO NOTHING;

INSERT INTO vendor_workflows
    (vendor_category_id, code, name, description, is_default)
SELECT id, 'dekorasi_default', 'Decoration Workflow',
       'Lead hingga setup dan dismantle', TRUE
FROM vendor_categories WHERE slug = 'dekorasi'
ON CONFLICT (vendor_category_id, code) DO NOTHING;

INSERT INTO vendor_workflows
    (vendor_category_id, code, name, description, is_default)
SELECT id, 'mua_default', 'MUA Workflow',
       'Lead hingga makeup selesai', TRUE
FROM vendor_categories WHERE slug = 'mua'
ON CONFLICT (vendor_category_id, code) DO NOTHING;

INSERT INTO vendor_workflows
    (vendor_category_id, code, name, description, is_default)
SELECT id, 'wo_default', 'Wedding Organizer Workflow',
       'Planning hingga evaluasi event', TRUE
FROM vendor_categories WHERE slug = 'wedding-organizer'
ON CONFLICT (vendor_category_id, code) DO NOTHING;

INSERT INTO workflow_stages
    (workflow_id, code, name, display_order, is_terminal)
SELECT vw.id, x.code, x.name, x.display_order, x.is_terminal
FROM (VALUES
('catering_default','lead','Lead',1,FALSE),
('catering_default','quotation','Quotation',2,FALSE),
('catering_default','booking','Booking',3,FALSE),
('catering_default','dp_paid','DP Paid',4,FALSE),
('catering_default','preparation','Preparation',5,FALSE),
('catering_default','production','Production',6,FALSE),
('catering_default','event','Event',7,FALSE),
('catering_default','completed','Completed',8,TRUE),

('photography_default','lead','Lead',1,FALSE),
('photography_default','quotation','Quotation',2,FALSE),
('photography_default','booking','Booking',3,FALSE),
('photography_default','photoshoot','Photoshoot',4,FALSE),
('photography_default','editing','Editing',5,FALSE),
('photography_default','client_review','Client Review',6,FALSE),
('photography_default','delivery','Delivery',7,FALSE),
('photography_default','completed','Completed',8,TRUE),

('dekorasi_default','lead','Lead',1,FALSE),
('dekorasi_default','survey','Venue Survey',2,FALSE),
('dekorasi_default','quotation','Quotation',3,FALSE),
('dekorasi_default','booking','Booking',4,FALSE),
('dekorasi_default','design','Design',5,FALSE),
('dekorasi_default','preparation','Preparation',6,FALSE),
('dekorasi_default','setup','Setup',7,FALSE),
('dekorasi_default','event','Event',8,FALSE),
('dekorasi_default','dismantle','Dismantle',9,FALSE),
('dekorasi_default','completed','Completed',10,TRUE),

('mua_default','lead','Lead',1,FALSE),
('mua_default','consultation','Consultation',2,FALSE),
('mua_default','booking','Booking',3,FALSE),
('mua_default','preparation','Preparation',4,FALSE),
('mua_default','makeup','Makeup Session',5,FALSE),
('mua_default','completed','Completed',6,TRUE),

('wo_default','lead','Lead',1,FALSE),
('wo_default','meeting','Meeting',2,FALSE),
('wo_default','proposal','Proposal',3,FALSE),
('wo_default','booking','Booking',4,FALSE),
('wo_default','planning','Planning',5,FALSE),
('wo_default','technical_meeting','Technical Meeting',6,FALSE),
('wo_default','event','Event',7,FALSE),
('wo_default','evaluation','Evaluation',8,FALSE),
('wo_default','completed','Completed',9,TRUE)
) AS x(workflow_code, code, name, display_order, is_terminal)
JOIN vendor_workflows vw ON vw.code = x.workflow_code
ON CONFLICT (workflow_id, code) DO UPDATE SET
    name = EXCLUDED.name,
    display_order = EXCLUDED.display_order,
    is_terminal = EXCLUDED.is_terminal;

-- =============================================================================

-- 40. DEFAULT SUBSCRIPTION PLANS
-- ---------------------------------------------------------------------------
INSERT INTO subscription_plans
(code, name, description, billing_interval, price, max_users, max_clients,
 max_bookings_per_month, max_storage_mb, features, is_active, is_public, sort_order)
VALUES
(
    'free', 'Free', 'Paket awal untuk vendor baru',
    'monthly', 0, 2, 50, 20, 512,
    '{"modules":["dashboard","clients","services","bookings","finance"]}'::jsonb,
    TRUE, TRUE, 1
),
(
    'pro', 'Pro', 'Paket untuk vendor yang sudah aktif',
    'monthly', 149000, 10, 1000, 200, 5120,
    '{"modules":["all_core","inventory","menu","equipment","decoration","mua_artists","rundown","reports"]}'::jsonb,
    TRUE, TRUE, 2
),
(
    'business', 'Business', 'Paket untuk vendor dengan operasional besar',
    'monthly', 299000, 30, 5000, 1000, 20480,
    '{"modules":["all"],"priority_support":true,"advanced_reports":true}'::jsonb,
    TRUE, TRUE, 3
)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    billing_interval = EXCLUDED.billing_interval,
    price = EXCLUDED.price,
    max_users = EXCLUDED.max_users,
    max_clients = EXCLUDED.max_clients,
    max_bookings_per_month = EXCLUDED.max_bookings_per_month,
    max_storage_mb = EXCLUDED.max_storage_mb,
    features = EXCLUDED.features,
    is_active = EXCLUDED.is_active,
    is_public = EXCLUDED.is_public,
    sort_order = EXCLUDED.sort_order;

-- =============================================================================
-- END V3.1
-- =============================================================================
